#!/home/czechen/Projects/Deep_Learning/NPFL/bin/python3
import argparse
import datetime
import os
import re

import torch
import torchmetrics

import npfl138
npfl138.require_version("2425.7.2")
from npfl138.datasets.morpho_dataset import MorphoDataset
from npfl138.datasets.morpho_analyzer import MorphoAnalyzer

# TODO: Define reasonable defaults and optionally more parameters.
# Also, you can set the number of threads to 0 to use all your CPU cores.
parser = argparse.ArgumentParser()
parser.add_argument("--batch_size", default=64, type=int, help="Batch size.")
parser.add_argument("--epochs", default=40, type=int, help="Number of epochs.")
parser.add_argument("--cle_dim", default=256, type=int, help="CLE embedding dimension.")
parser.add_argument("--rnn_dim", default=512, type=int, help="RNN layer dimension.")
parser.add_argument("--we_dim", default=128, type=int, help="Word embedding dimension.")
parser.add_argument("--word_masking", default=0.3, type=float, help="Mask words with the given probability.")
parser.add_argument("--max_sentences", default=None, type=int, help="Maximum number of sentences to load.")
parser.add_argument("--seed", default=42, type=int, help="Random seed.")
parser.add_argument("--threads", default=1, type=int, help="Maximum number of threads to use.")

class Model(npfl138.TrainableModule):
    class MaskElements(torch.nn.Module):
        """A layer randomly masking elements with a given value."""
        def __init__(self, mask_probability, mask_value):
            super().__init__()
            self._mask_probability = mask_probability
            self._mask_value = mask_value

        def forward(self, inputs: torch.Tensor) -> torch.Tensor:
            # Only mask during training and when the mask probability is non-zero.
            if self.training and self._mask_probability:
                # TODO: Generate a mask tensor of `torch.float32`s of the same shape
                # as `inputs` using either `torch.rand` or `torch.rand_like`.
                # Then replace the inputs elements whose mask value is less than
                # `self._mask_probability` with the value of `self._mask_value`.
                mask = (torch.rand(inputs.shape,dtype=torch.float32) > self._mask_probability).to(torch.int)
                mask_new_value = self._mask_value*(mask < 1).to(torch.int)
                inputs = inputs.to('cpu')*mask.to('cpu') + mask_new_value.to('cpu')
            return inputs

    def __init__(self, args: argparse.Namespace, train: MorphoDataset.Dataset) -> None:
        super().__init__()
        self._args = args
        # Create all needed layers.
        # TODO: Create a word masking layer `self.MaskElements` with the given
        # `args.word_masking` probability and `MorphoDataset.UNK` as the masking value.
        self._word_masking = self.MaskElements(args.word_masking,MorphoDataset.UNK)

        # TODO: Create a `torch.nn.Embedding` layer for embedding the character ids
        # from `train.words.char_vocab` to dimensionality `args.cle_dim`.
        self._char_embedding = torch.nn.Embedding(len(train.words.char_vocab),args.cle_dim)

        # TODO: Create a bidirectional `torch.nn.GRU` layer processing the character
        # embeddings, producing output of dimensionality `args.cle_dim`; again, also pass
        # `batch_first=True` to the constructor.
        self._char_rnn = torch.nn.GRU(args.cle_dim,args.cle_dim,batch_first=True,bidirectional=True)

        # TODO(tagger_we): Create a `torch.nn.Embedding` layer, embedding the word ids
        # from `train.words.string_vocab` to dimensionality `args.we_dim`.
        self._word_embedding = torch.nn.Embedding(len(train.words.string_vocab),args.we_dim)

        # TODO: Create an RNN layer, either `torch.nn.LSTM` or `torch.nn.GRU` depending
        # on `args.rnn`. The layer should be bidirectional (`bidirectional=True`) with
        # dimensionality `args.rnn_dim`, and you should also pass `batch_first=True` to
        # the constructor. In the forward pass, the layer will process the word embeddings
        # generated by the `self._word_embedding` layer, **now concatenated with the
        # character-level embeddings**, and we will sum the forward and backward outputs.
        self._word_rnn = torch.nn.LSTM(args.we_dim+2*args.cle_dim, args.rnn_dim, bidirectional=True,batch_first=True)
        self._word_rnn_dropout = torch.nn.Dropout(0.5)
        self._second_LSTM = torch.nn.LSTM(args.rnn_dim,args.rnn_dim, batch_first=True)
        # TODO(tagger_we): Create an output linear layer (`torch.nn.Linear`) processing the RNN output,
        # producing logits for tag prediction; `train.tags.string_vocab` is the tag vocabulary.
        self._output_layer = torch.nn.Linear(args.rnn_dim,len(train.tags.string_vocab))

    def forward(self, word_ids: torch.Tensor, unique_words: torch.Tensor, word_indices: torch.Tensor) -> torch.Tensor:
        # TODO: Mask the input `word_ids` using the `self._word_masking` layer.
        hidden = self._word_masking(word_ids)

        # TODO: Embed the masked word IDs in `hidden` using the word embedding layer.
        hidden = self._word_embedding(hidden)

        # TODO: Embed the `unique_words` using the character embedding layer.
        cle = self._char_embedding(unique_words)

        # TODO: Pass the character embeddings through the character-level RNN.
        # As during word-level RNN, start by packing the input sequence.
        lengths = (unique_words > 0).to(torch.int)
        lengths = torch.sum(lengths,dim=1).cpu()
        cle_packed = torch.nn.utils.rnn.pack_padded_sequence(cle, lengths,batch_first=True,enforce_sorted=False)

        # TODO: Pass the `PackedSequence` through the character RNN, obtaining fixed-size
        # representation of every unique word in the batch. Then, concatenate the states
        # of the forward and backward directions (in this order).
        output,cle = self._char_rnn(cle_packed)
        cle = torch.cat((cle[0],cle[1]),1)

        # TODO: With `cle` being the character-level embeddings of the unique words
        # of shape `[num_unique_words, 2 * cle_dim]`, create the representation of the
        # (not necessary unique) sentence words by indexing the character-level
        # embeddings with the `word_indices`. The result should have a shape
        # `[batch_size, max_sentence_length, 2 * cle_dim]`. You can use for example
        # the `torch.nn.functional.embedding` function.
        cle = torch.nn.functional.embedding(word_indices,cle)

        # TODO: Concatenate the word embeddings with the character-level embeddings (in this order).
        hidden = torch.cat((hidden,cle),dim=2)

        # TODO(tagger_we): Process the embeddings through the RNN layer. Because the sentences
        # have different length, you have to use `torch.nn.utils.rnn.pack_padded_sequence`
        # to construct a variable-length `PackedSequence` from the input. You need to compute
        # the length of each sentence in the batch (by counting non-`MorphoDataset.PAD` tokens);
        # note that these lengths must be on CPU, so you might need to use the `.cpu()` method.
        # Finally, also pass `batch_first=True` and `enforce_sorted=False` to the call.
        lengths = (word_ids > 0).to(torch.int)
        lengths = torch.sum(lengths,dim=1).cpu()
        packed = torch.nn.utils.rnn.pack_padded_sequence(hidden, lengths,batch_first=True,enforce_sorted=False)

        # TODO(tagger_we): Pass the `PackedSequence` through the RNN, choosing the appropriate output.
        packed, others = self._word_rnn(packed)
        # TODO(tagger_we): Unpack the RNN output using the `torch.nn.utils.rnn.pad_packed_sequence` with
        # `batch_first=True` argument. Then sum the outputs of forward and backward directions.
        hidden,lenghts = torch.nn.utils.rnn.pad_packed_sequence(packed,batch_first=True)
        hidden = hidden[...,0:self._args.rnn_dim] + hidden[...,self._args.rnn_dim:]
        packed = self._word_rnn_dropout(hidden)
        packed = torch.nn.utils.rnn.pack_padded_sequence(packed, lengths,batch_first=True,enforce_sorted=False)
        second, others = self._second_LSTM(packed)
        second,lenghts = torch.nn.utils.rnn.pad_packed_sequence(second,batch_first=True)
        hidden = hidden + second
        # TODO(tagger_we): Pass the RNN output through the output layer. Such an output has a shape
        # `[batch_size, sequence_length, num_tags]`, but the loss and the metric expect
        # the `num_tags` dimension to be in front (`[batch_size, num_tags, sequence_length]`),
        # so you need to reorder the dimensions.
        hidden = self._output_layer(hidden)

        return torch.transpose(hidden,-1,-2)


class TrainableDataset(npfl138.TransformedDataset):
    def transform(self, example):
        # TODO(tagger_we): Construct a single example, each consisting of the following pair:
        # - a PyTorch tensor of integer ids of input words as input,
        # - a PyTorch tensor of integer tag ids as targets.
        # To create the ids, use `string_vocab` of `self.dataset.words` and `self.dataset.tags`.
        word_ids = torch.tensor(self.dataset.words.string_vocab.indices(example['words']))
        tag_ids = torch.tensor(self.dataset.tags.string_vocab.indices(example['tags'])) 
        # Note that compared to `tagger_we`, we also return the original
        # words in order to be able to compute the character-level embeddings.
        return word_ids, example["words"], tag_ids

    def collate(self, batch):
        # Construct a single batch, where `data` is a list of examples
        # generated by `transform`.
        word_ids, words, tag_ids = zip(*batch)
        # TODO(tagger_we): Combine `word_ids` into a single tensor, padding shorter
        # sequences to length of the longest sequence in the batch with zeros
        # using `torch.nn.utils.rnn.pad_sequence` with `batch_first=True` argument.
        word_ids = torch.nn.utils.rnn.pad_sequence(word_ids,batch_first=True)
        # TODO: Create required inputs for the character-level embeddings using
        # the provided `self.dataset.cle_batch` function on `words`. The function
        # returns a pair of two PyTorch tensors:
        # - `unique_words` with shape `[num_unique_words, max_word_length]` containing
        #   each unique word as a sequence of character ids,
        # - `words_indices` with shape `[num_sentences, max_sentence_length]`
        #   containing for every word its index in `unique_words`.
        unique_words, words_indices = self.dataset.cle_batch(words)
        # TODO(tagger_we): Process `tag_ids` analogously to `word_ids`.
        tag_ids =  torch.nn.utils.rnn.pad_sequence(tag_ids,batch_first=True)
        return (word_ids, unique_words, words_indices), tag_ids

def main(args: argparse.Namespace) -> None:
    # Set the random seed and the number of threads.
    npfl138.startup(args.seed, args.threads)
    npfl138.global_keras_initializers()

    # Create logdir name.
    args.logdir = os.path.join("logs", "{}-{}-{}".format(
        os.path.basename(globals().get("__file__", "notebook")),
        datetime.datetime.now().strftime("%Y-%m-%d_%H%M%S"),
        ",".join(("{}={}".format(re.sub("(.)[^_]*_?", r"\1", k), v) for k, v in sorted(vars(args).items())))
    ))

    # Load the data. Using analyses is only optional.
    morpho = MorphoDataset("czech_pdt",max_sentences=args.max_sentences)
    analyses = MorphoAnalyzer("czech_pdt_analyses") 

    train = TrainableDataset(morpho.train).dataloader(batch_size=args.batch_size, shuffle=True)
    dev = TrainableDataset(morpho.dev).dataloader(batch_size=args.batch_size)
    test = TrainableDataset(morpho.test).dataloader(batch_size=args.batch_size)
    # Create the model and train.
    model = Model(args, morpho.train)

    model.configure(
        # TODO: Create the Adam optimizer.
        optimizer=torch.optim.Adam(model.parameters()),
        # TODO: Use the usual `torch.nn.CrossEntropyLoss` loss function. Additionally,
        # pass `ignore_index=morpho.PAD` to the constructor so that the padded
        # tags are ignored during the loss computation. Note that the loss
        # expects the input to be of shape `[batch_size, num_tags, sequence_length]`.
        loss=torch.nn.CrossEntropyLoss(ignore_index=morpho.PAD,label_smoothing=0.01),
        # TODO: Create a `torchmetrics.Accuracy` metric, passing "multiclass" as
        # the first argument, `num_classes` set to the number of unique tags, and
        # again `ignore_index=morpho.PAD` to ignore the padded tags.
        metrics={"accuracy": torchmetrics.Accuracy('multiclass',num_classes=len(morpho.train.tags.string_vocab),ignore_index=morpho.PAD)},
        logdir=args.logdir,
    )

    logs = model.fit(train, dev=dev, epochs=args.epochs)

    # Generate test set annotations, but in `args.logdir` to allow parallel execution.
    os.makedirs(args.logdir, exist_ok=True)
    with open(os.path.join(args.logdir, "tagger_competition.txt"), "w", encoding="utf-8") as predictions_file:
        # TODO: Predict the tags on the test set. The following code assumes you use the same
        # output structure as in `tagger_we`, i.e., that for each sentence, the predictions are
        # a Numpy vector of shape `[num_tags, sentence_len_or_more]`, where `sentence_len_or_more`
        # is the length of the corresponding batch. (FYI, if you instead used the `packed` variant,
        # the prediction for each sentence is a vector of shape `[exactly_sentence_len, num_tags]`.)
        predictions = model.predict(test, data_with_labels=True)

        for predicted_tags, words in zip(predictions, morpho.test.words.strings):
            for predicted_tag in predicted_tags[:, :len(words)].argmax(axis=0):
                print(morpho.train.tags.string_vocab.string(predicted_tag), file=predictions_file)
            print(file=predictions_file)
        
if __name__ == "__main__":
    main_args = parser.parse_args([] if "__file__" not in globals() else None)
    main(main_args)
